// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdhojsbafxaulzlkwxkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkaG9qc2JhZnhhdWx6bGt3eGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjIzOTUsImV4cCI6MjA2NzY5ODM5NX0.8HeqiiFeS2wOLJ-pHZ5xttS3h7POfuA7OY4-2DTRces";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});